steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-f', 'Dockerfile.patch', '-t', 'us-central1-docker.pkg.dev/social-media-automation-5c9db/cloud-run-source-deploy/lds-quotes-publisher:multiformat-v4', '.']
images:
  - us-central1-docker.pkg.dev/social-media-automation-5c9db/cloud-run-source-deploy/lds-quotes-publisher:multiformat-v4
