steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-f', 'cloud_jobs/beam/Dockerfile', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/beam-publisher:beam-interactive-$BUILD_ID', '.']
images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/beam-publisher:beam-interactive-$BUILD_ID
timeout: 600s
